# Site settings
title: Atte Vuorinen
email: attevuorinen@gmail.com
author: Atte Vuorinen
description: ""
baseurl: ""
url: "http://avuorinen.github.io/"
google_analytics: UA-54772984-1

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
