title: "AV"
author: "Atte Vuorinen"
description: ""
#subheading: "Really cool blog about ... something"
more: "read more"
url: "http://avuorinen.github.io"
#baseurl: "" # comment out if in root directory

comments:
#    disqus: ""
#    isso: "comments.mysite.org"

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#323252" #181818 #3F51B5 #38384A #3C3C65 #323252
    #headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#3C3C65" #"#222222"
        image-alpha: 0.985

links:
  - github: "https://github.com/avuorinen"
  - linkedin: "https://www.linkedin.com/pub/atte-vuorinen/7b/675/888"
  #- twitter: "https://twitter.com/"
  #- google-plus: "https://plus.google.com/"
  #- reddit: "https://www.reddit.com/user/"
  #- youtube: "https://www.youtube.com/user/"
  #- steam: "http://steamcommunity.com/id/"

paginate: 10
excerpt_separator: "\n\n\n" # excerpt ends after two blank lines
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
plugins:
  - jekyll-feed # include feed plugin (supported by gh-pages)
  - jekyll-paginate
