# Site settings
title: Atte Vuorinen - Work in Progress!
email: attevuorinen@gmail.com
author: Atte Vuorinen
description: ""
baseurl: ""
url: "http://avuorinen.github.io/"
google_analytics: 

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
